name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_DATABASE: blog_service
  DB_USER: root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ">=1.18.0"

      - name: Set up MySQL client
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: ${{env.DB_DATABASE}}
          mysql root password: ${{ secrets.DB_PASSWORD }}
          mysql user: ${{env.DB_USER}}
          mysql password: ${{ secrets.DB_PASSWORD }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...